version: '3.5'

services:
  consignment-cli:
    build: ./consignment-cli

  consignment-service:
    restart: always # ensures the container will restart on crash
    container_name: "consignment-service"
    build: ./consignment-service
    ports:
      - 50051 # exposing this port on the docker network only, not host
    links:
      - datastore
    depends_on:
      - datastore
    networks:
      - shippy-backend-tier
      - consignment-tier
    environment:
      DB_HOST: "datastore:27017"
      MICRO_ADDRESS: ":50051"

  vessel-service:
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      DB_HOST: "datastore:27017"

  user-service:
    build: ./user-service
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"

  datastore:
    image: mongo:latest
    container_name: datastore
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db # ensures data persistence between restarting
    networks:
      - consignment-tier
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null

    database:
      image: postgres
      ports:
        - 5432:5432

networks:
  consignment-tier:
    name: consignment-tier
  shippy-backend-tier:
    name: shippy-backend-tier
